### ISSUE TITLE
Reloading a cluster image produces a featureless image

### ISSUE THREAD

**Issue by bldrvnlw** [ManiVaultStudio/MeanShiftClustering#17]
The mean shift cluster image on the right was reloaded it should look like the one on the left.

![image](https://github.com/ManiVaultStudio/MeanShiftClustering/assets/2050743/5dc4d1ad-2d55-4bcd-810b-63ddbd1a15de)

This was created on the sun data 25% downsampled.

**Comment by ThomasKroes** [comment]
Closing because this issue has been solved in [this](https://github.com/ManiVaultStudio/core/pull/626) core pr.
